<div class="title-bar" data-responsive-toggle="example-animated-menu" data-hide-for="medium">
<button class="menu-icon" type="button" data-toggle></button>
<div class="title-bar-title"><?php echo APP::config('nazivAPP'); ?></div>
</div>
<div class="top-bar" id="example-animated-menu" data-animate="hinge-in-from-top spin-out">
    <div class="top-bar-right">
        <ul class="menu">
            <li class="menu-text show-for-large">
            <?php echo APP::config('nazivAPP'); ?>
            </li>
            <li>
            <?php if(!isset($_SESSION['admin'])): ?>
                <a href="index/prijava">Admin</a>
            <?php else:?>
                <a href="/index/odjava">Odjavi 
                <?php echo $_SESSION['admin']->username ?></a>
            <?php endif;?>
                </li>
            <?php if(isset($_SESSION['admin'])):?>
                <li><a href="/item/index">Itemi</a></li>
            <?php endif; ?>
        </ul>
    </div>
</div>